### ISSUE TITLE
能加入浏览器限制吗

### ISSUE THREAD

**Issue by qq8554650** [barats/ohUrlShortener#14]
比如限微信  限移动端

**Comment by barats** [comment]
具体需求是啥？可以详细说说吗？

**Comment by qq8554650** [comment]
![image](https://user-images.githubusercontent.com/22789241/192186948-006f7f81-d9df-4a0b-8bc4-105f815478fb.png)
http://c.i110.net/CvXQ
这个就只能微信打开
如果需要可以提供后台

**Comment by barats** [comment]
不用看后台了，我大概知道是什么意思了。

等我有时间了分析下这个需求怎么实现，个人觉得还是蛮有意义的。

**Comment by barats** [comment]
由于前期设计的时候，没考虑过这种情况。
分析了一下，如果现在要实现它的话，需要在 302 之前再做一次数据库查询。
这样速度就会慢很多。
所以，这个需求我暂时挂起。等我再下个阶段考虑怎么样优化吧！
