### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by nullniverse** [barats/ohUrlShortener#16]
Hello!

I'm the same user who submitted the issue https://github.com/barats/ohUrlShortener/issues/11 before, but using my personal account.

I've translated this project to english, and I would love to contribute towards translating it to ru_RU or pt_BR. 

Do you know if there's a way to collaborate towards that goal? 

I've already translated to en_US (but this repo is outdated with that issues still presenting). 

Thanks!

**Comment by barats** [comment]
Collaboration of any kind to this project is warmly welcomed.  (Thanks for ur issue before)

> I've already translated to en_US (but this repo is outdated with that issues still presenting).

It's not outdated, I promise you that. I've been kept busy with my work is all. And ohUrlShortener is a personal work, I have to find some spare time to finish the rest issues. 

BTW: Before you make any contribution to this repo( especially before you make a pull request), please read [ohUrlShortener Contributor License Agreement](https://github.com/barats/ohUrlShortener/blob/main/CLA.md) carefully. I only accept PRs if you agree to these terms. I found NO time to translate these terms into English, so please translate it via Google Translate :)

**Comment by nullniverse** [comment]
Thank you so much barats!

Oh, and about "outdated" I was referring to my fork of your project :sweat_smile: 

I'll read the terms and start contributing ASAP! Thanks a lot.

**Comment by barats** [comment]
I saw your forked version of ohUrlShortener, nice work there. 
So nice to let me know that I'm not alone. 
Looking forward to your PRs.

**Comment by barats** [comment]
Maybe it's time to start Internationalization.
