### ISSUE TITLE
remove all code point to btcd in README

### ISSUE THREAD

**Issue by houseme** [barats/ohUrlShortener#2]
This package is now a sub-package in the [btcutil](https://github.com/btcsuite/btcd/tree/master/btcutil) directory of the [btcd](https://github.com/btcsuite/btcd) repository.

https://github.com/btcsuite/btcutil
[PR](https://github.com/btcsuite/btcutil/commit/27c39e0ab4f9d19a7ccb4ae91929e9b180172212)

**Comment by barats** [comment]
Haven't mentioned btcutil in README, but I will. And when I do, I'll keep it in mind. 
Thanks.
