### ISSUE TITLE
请问如何配置url_prefix 和端口以支持短域名

### ISSUE THREAD

**Issue by sanrenx** [barats/ohUrlShortener#21]
我修改了 url_prefix = http://xxx.vn (我的一个短域名 已经配置dns解析到服务器) 但是打开管理后台 依旧是 http://localhost:9091/
请问如何发布到生产服务器以使用，开发调试没问题，请给点指点发布到生产配置自己的短域名需要配置哪些？谢谢

**Comment by sanrenx** [comment]
https证书免费的也申请了，如果需要https支持又改如何配置呢？

**Comment by barats** [comment]
> 我修改了 url_prefix = http://xxx.vn (我的一个短域名 已经配置dns解析到服务器) 但是打开管理后台 依旧是 http://localhost:9091/ 请问如何发布到生产服务器以使用，开发调试没问题，请给点指点发布到生产配置自己的短域名需要配置哪些？谢谢

启动程序之前，需要改根目录下的 config.ini 配置文件，这个配置就在里面的。

> https证书免费的也申请了，如果需要https支持又改如何配置呢？

https 应该通过 nginx 配置啊，短链接系统本身是不处理这些事儿的

**Comment by sanrenx** [comment]
@barats  嗯嗯 今早尝试nginx返代理 可以了 不过修改config.ini 并没起作用，我用的 local_build , 最后修改了 docker_config.ini才实现

**Comment by barats** [comment]
> @barats 嗯嗯 今早尝试nginx返代理 可以了 不过修改config.ini 并没起作用，我用的 local_build , 最后修改了 docker_config.ini才实现

对，如果是用 docker 跑的话，需要修改 {project_root}/docker 下面的配置才可以

感谢使用，有问题欢迎再提。
