### ISSUE TITLE
容器启动配置好后设置短链访问出现404

### ISSUE THREAD

**Issue by fireinrain** [barats/ohUrlShortener#22]
你好，开发大大 我按照文档中的部署好后，添加新的链接，然后访问后出现404:
截图如下:
![image](https://user-images.githubusercontent.com/14249262/234470211-714e770f-1245-45af-a1be-b94f8dd8ea34.png)

**Comment by barats** [comment]
显然的事啊，因为 `devops.131433.xyz` 不是短链接

通过管理后端登录之后，新建短链接再访问试试。

**Comment by fireinrain** [comment]
> 显然的事啊，因为 `devops.131433.xyz` 不是短链接
> 
> 通过管理后端登录之后，新建短链接再访问试试。

我就是从新建的短链那边点击的 点击就跳转这个

如图：
![image](https://user-images.githubusercontent.com/14249262/234592060-d05e295c-2f3c-4a7c-95b2-1e25e63f9a2e.png)

**Comment by fireinrain** [comment]
![image](https://user-images.githubusercontent.com/14249262/234592457-573a0eca-fed9-4f52-9f5b-6a568f0fb9c3.png)

**Comment by fireinrain** [comment]
是我数据库没配置好吗，url 是正确的 但是一点击就跳转404的那个

**Comment by barats** [comment]
短链接前缀是 `urls.141433.xyz` ，短链接是 `Hov5ZzBN` 

如果都已经生成了，数据库配置和 Redis 应该都是正常的

点击 [http://urls.141433.xyz/Hov5ZzBN](http://urls.141433.xyz/Hov5ZzBN) 就应该跳转到目标链接

我点了这个链接，但是无法打开，应该是你的 nginx 配置不对吧

**Comment by fireinrain** [comment]
> 短链接前缀是 `urls.141433.xyz` ，短链接是 `Hov5ZzBN`
> 
> 如果都已经生成了，数据库配置和 Redis 应该都是正常的
> 
> 点击 http://urls.141433.xyz/Hov5ZzBN 就应该跳转到目标链接
> 
> 我点了这个链接，但是无法打开，应该是你的 nginx 配置不对吧

我在排查排查
