### ISSUE TITLE
Are you going to support mysql database storage?

### ISSUE THREAD

**Issue by houseme** [barats/ohUrlShortener#3]
Are you going to support mysql database storage?

**Comment by barats** [comment]
Is it really necessary? 

If it does, I may have some spare time to get it done.

**Comment by houseme** [comment]
> Is it really necessary?
> 
> If it does, I may have some spare time to get it done.

Waiting for your good news.

**Comment by houseme** [comment]
这个2.0支持吗？

**Comment by barats** [comment]
> 

暂时没规划到 2.0 里面，再下个版本找机会吧！

**Comment by barats** [comment]
from Gitee https://gitee.com/barat/ohurlshortener/issues/I5G0L4
