### ISSUE TITLE
Golang redis 语法错误：ERR syntax error

### ISSUE THREAD

**Issue by houseme** [barats/ohUrlShortener#4]
https://github.com/barats/ohUrlShortener/blob/7d950e9c4e638ea9b832bc413b90ad6e77e1cc66/storage/base_redis.go#L53

使用的包："github.com/go-redis/redis/v8"

错误的语法:

```go
if err := rd.Set(ctx, key, val, -1).Err(); err != nil {
    panic(err)
}
```

结果：
```html
低版本的`redis`不支持 `-1`来设置ttl,出现语法的版本为<5.0
升级版本即可
```

如果开发环境能能正常运行，到测试环境就拉胯，大概率是环境问题
目前阿里云的集群和主从的5.0.5版都有这个问题。

**Comment by barats** [comment]
> 目前阿里云的集群和主从的5.0.5版都有这个问题。

关于 Redis 集群的问题，我确实没测试过。
问题清楚了，我会处理这个问题，仅会更新。

thanks

**Comment by barats** [comment]
我记得，Redis 版本的问题，我之前加过一个备注。
刚看了下 git log ，果然是有备注。
但是不知道为什么，我竟然把那个注释删掉了。

![image](https://user-images.githubusercontent.com/12779645/172297856-10724719-a7e9-4bde-9ea1-78e59b374eee.png)

Anyway，Redis 最低版本就先 6.0 吧！

我先抽时间处理下 captcha 支持 Redis 的那个问题，再把集群测试下然后发个新版本。
