### ISSUE TITLE
验证码只能单机使用？

### ISSUE THREAD

**Issue by houseme** [barats/ohUrlShortener#5]
多台机部署时，验证码加载失败，刷新又显示，发现验证码的值时存在，内存中的。作者有打算替换验证码的包吗？

**Comment by barats** [comment]
还没真没有考虑集群的情况，这个问题也可以 tag 一下，找个机会把验证码让到 Redis 就可以了。

这段时间暂时没太多时间处理

**Comment by barats** [comment]
打算推出一个 2.0 的版本，支持 captcha 存储到 Redis 以支持 ohUrlShortener 集群部署

同时，1.x 单机版本也将继续存在

时间方面，大致不会晚于06月20日发布。

**Comment by barats** [comment]
已支持 Reids 存储验证码，查看 PR https://github.com/barats/ohUrlShortener/pull/19 

过几天再把 Redis Cluster 的问题解决后，一起发布 v1.9 版本。
